### PR TITLE
Update

### LINKED ISSUE #17: doctest! seems to not work any more?
Consider the following:

```
$ tree -I target
.
├── Cargo.lock
├── Cargo.toml
├── README.md
└── src
    └── lib.rs

1 directory, 4 files

$ cat Cargo.toml
[package]
name = "doc-comment-fail"
version = "0.1.0"
authors = ["Andrew Gallant <jamslam@gmail.com>"]
edition = "2018"

[dependencies]
doc-comment = "0.3.1"

$ cat src/lib.rs
#[cfg(test)]
doc_comment::doctest!("../README.md");

pub fn something() {}

$ cat README.md
```rust
fn main() {
  this is an invalid program
}
```

Since my Rust program in my README is invalid, I expected `cargo test` to fail. But instead, it passes and does not seem to run any tests:

```
$ cargo test
    Finished test [unoptimized + debuginfo] target(s) in 0.01s
     Running target/debug/deps/doc_comment_fail-fe51e9186885559c

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

   Doc-tests doc-comment-fail

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out
```

Did something break this functionality or am I perhaps just doing something wrong?

If I run `cargo expand`, then it shows the macro is still expanding seemingly correctly:

```
$ cargo expand --color never --lib --tests
   Compiling doc-comment-fail v0.1.0 (/tmp/doc-comment-fail)
    Finished test [unoptimized + debuginfo] target(s) in 0.04s

#![feature(prelude_import)]
#[prelude_import]
use std::prelude::v1::*;
#[macro_use]
extern crate std;
///```rust
///fn main() {
///  this is an invalid program
///}
///```
extern "C" {}
pub fn something() {}
#[main]
pub fn main() -> () {
    extern crate test;
    test::test_main_static(&[])
}
```

If I inline the relevant bits of `cargo expand` into `src/lib.rs` manually, then the test fails, as I expect:

```
$ cat src/lib.rs
///```rust
///fn main() {
///  this is an invalid program
///}
///```
extern "C" {}

pub fn something() {}

$ cargo test
   Compiling doc-comment-fail v0.1.0 (/tmp/doc-comment-fail)
    Finished test [unoptimized + debuginfo] target(s) in 0.19s
     Running target/debug/deps/doc_comment_fail-fe51e9186885559c

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

   Doc-tests doc-comment-fail

running 1 test
test src/lib.rs -  (line 1) ... FAILED

failures:

---- src/lib.rs -  (line 1) stdout ----
error: expected one of `!`, `.`, `::`, `;`, `?`, `{`, `}`, or an operator, found `is`
 --> src/lib.rs:3:8
  |
3 |   this is an invalid program
  |        ^^ expected one of 8 possible tokens

error: aborting due to previous error

Couldn't compile the test.

failures:
    src/lib.rs -  (line 1)

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out

error: test failed, to rerun pass '--doc'
```

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Fixes #17 

Is it enough for you @BurntSushi or do you have something else in mind?

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
I'll maybe write a small blog post about it to make this fact more widely known.

**Review by BurntSushi — APPROVED** [review]
Perfect! And yes, a blog post sounds great. :-) I think you nailed this particular problem!

**Comment by GuillaumeGomez** [comment]
Cool! Writing it then. Meanwhile, merging and publishing the new crate version.

**Comment by BurntSushi** [comment]
Oh, wait, perhaps I _wasn't_ going crazy. It looks like `cfg(doctest)` was just recently stabilized? https://github.com/rust-lang/rust/pull/63803

Does that mean it _used_ to work with `cfg(test)` but now it no longer does?

**Comment by GuillaumeGomez** [comment]
Yep, it's been a huge debate. Don't know why, I thought you've been part of it... But no: you're not crazy. It's stable only since 1.40! I made the blog post btw: https://blog.guillaume-gomez.fr/articles/2020-03-07+cfg%28doctest%29+is+stable+and+you+should+use+it

**Pull request merged**
